- name: Set up and configure NGINX
  hosts: all
  become: true
  roles:
    - nginx_setup
  tasks:
    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - curl
        - git
        - ufw
        - htop
        - iftop



